[2025-07-02T03:30:25.291+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T03:30:25.306+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:30:18.431947+00:00 [queued]>
[2025-07-02T03:30:25.315+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:30:18.431947+00:00 [queued]>
[2025-07-02T03:30:25.316+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T03:30:25.325+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_staging> on 2025-07-02 03:30:18.431947+00:00
[2025-07-02T03:30:25.335+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=672) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T03:30:25.336+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_staging', 'manual__2025-07-02T03:30:18.431947+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmpr97ox6eq']
[2025-07-02T03:30:25.338+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask run_dbt_staging
[2025-07-02T03:30:25.337+0000] {standard_task_runner.py:72} INFO - Started process 674 to run task
[2025-07-02T03:30:25.400+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:30:18.431947+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T03:30:25.461+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T03:30:18.431947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T03:30:18.431947+00:00'
[2025-07-02T03:30:25.462+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T03:30:25.490+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-02T03:30:25.492+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:staging']
[2025-07-02T03:30:25.508+0000] {subprocess.py:86} INFO - Output:
[2025-07-02T03:30:25.519+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-07-02T03:30:25.519+0000] {subprocess.py:93} INFO - + dbt run --select tag:staging
[2025-07-02T03:30:28.492+0000] {subprocess.py:93} INFO - [0m03:30:28  Running with dbt=1.8.0
[2025-07-02T03:30:28.835+0000] {subprocess.py:93} INFO - [0m03:30:28  Registered adapter: postgres=1.8.2
[2025-07-02T03:30:28.923+0000] {subprocess.py:93} INFO - [0m03:30:28  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-07-02T03:30:29.806+0000] {subprocess.py:93} INFO - [0m03:30:29  Encountered an error:
[2025-07-02T03:30:29.809+0000] {subprocess.py:93} INFO - Compilation Error
[2025-07-02T03:30:29.810+0000] {subprocess.py:93} INFO -   Model 'model.dbt_driven_data.trusted_payment_data' (models/trusted_payment_data.sql) depends on a source named 'staging_source.dim_finance' which was not found
[2025-07-02T03:30:30.901+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-02T03:30:30.937+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-02T03:30:30.955+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=run_dbt_staging, run_id=manual__2025-07-02T03:30:18.431947+00:00, execution_date=20250702T033018, start_date=20250702T033025, end_date=20250702T033030
[2025-07-02T03:30:30.974+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T03:30:30.975+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task run_dbt_staging (Bash command failed. The command returned a non-zero exit code 2.; 674)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-02T03:30:31.033+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-02T03:30:31.066+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-02T03:30:31.069+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
