[2025-07-02T03:47:30.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T03:47:30.026+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:47:24.314809+00:00 [queued]>
[2025-07-02T03:47:30.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:47:24.314809+00:00 [queued]>
[2025-07-02T03:47:30.034+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T03:47:30.044+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_raw_data> on 2025-07-02 03:47:24.314809+00:00
[2025-07-02T03:47:30.055+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=923) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T03:47:30.057+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'load_raw_data', 'manual__2025-07-02T03:47:24.314809+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmp8ecgdd5b']
[2025-07-02T03:47:30.058+0000] {standard_task_runner.py:72} INFO - Started process 925 to run task
[2025-07-02T03:47:30.058+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask load_raw_data
[2025-07-02T03:47:30.108+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.load_raw_data manual__2025-07-02T03:47:24.314809+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T03:47:30.168+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='load_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T03:47:24.314809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T03:47:24.314809+00:00'
[2025-07-02T03:47:30.169+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T03:47:30.181+0000] {driven_data_pipeline.py:163} INFO - Starting data insertion from CSV to PostgreSQL...
[2025-07-02T03:47:30.201+0000] {driven_data_pipeline.py:211} INFO - Data insertion complete.
[2025-07-02T03:47:30.201+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-02T03:47:30.214+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T03:47:30.214+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_raw_data_pipeline, task_id=load_raw_data, run_id=manual__2025-07-02T03:47:24.314809+00:00, execution_date=20250702T034724, start_date=20250702T034730, end_date=20250702T034730
[2025-07-02T03:47:30.243+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-02T03:47:30.263+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-02T03:47:30.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
