[2025-07-02T03:47:31.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-02T03:47:31.275+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:47:24.314809+00:00 [queued]>
[2025-07-02T03:47:31.289+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:47:24.314809+00:00 [queued]>
[2025-07-02T03:47:31.289+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-07-02T03:47:31.309+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_staging> on 2025-07-02 03:47:24.314809+00:00
[2025-07-02T03:47:31.326+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=927) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-02T03:47:31.330+0000] {standard_task_runner.py:72} INFO - Started process 929 to run task
[2025-07-02T03:47:31.329+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_staging', 'manual__2025-07-02T03:47:24.314809+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/driven_data_pipeline.py', '--cfg-path', '/tmp/tmppxa88kia']
[2025-07-02T03:47:31.332+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask run_dbt_staging
[2025-07-02T03:47:31.414+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_staging manual__2025-07-02T03:47:24.314809+00:00 [running]> on host 24d4a3002b8f
[2025-07-02T03:47:31.531+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T03:47:24.314809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T03:47:24.314809+00:00'
[2025-07-02T03:47:31.533+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-02T03:47:31.577+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-02T03:47:31.587+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:staging']
[2025-07-02T03:47:31.622+0000] {subprocess.py:86} INFO - Output:
[2025-07-02T03:47:31.647+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-07-02T03:47:31.652+0000] {subprocess.py:93} INFO - + dbt run --select tag:staging
[2025-07-02T03:47:34.157+0000] {subprocess.py:93} INFO - [0m03:47:34  Running with dbt=1.8.0
[2025-07-02T03:47:34.461+0000] {subprocess.py:93} INFO - [0m03:47:34  Registered adapter: postgres=1.8.2
[2025-07-02T03:47:34.537+0000] {subprocess.py:93} INFO - [0m03:47:34  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-07-02T03:47:34.547+0000] {subprocess.py:93} INFO - [0m03:47:34  Encountered an error:
[2025-07-02T03:47:34.548+0000] {subprocess.py:93} INFO - Parsing Error
[2025-07-02T03:47:34.548+0000] {subprocess.py:93} INFO -   Error reading dbt_driven_data: source.yml - Runtime Error
[2025-07-02T03:47:34.548+0000] {subprocess.py:93} INFO -     Syntax error near line 5
[2025-07-02T03:47:34.549+0000] {subprocess.py:93} INFO -     ------------------------------
[2025-07-02T03:47:34.549+0000] {subprocess.py:93} INFO -     2  |
[2025-07-02T03:47:34.549+0000] {subprocess.py:93} INFO -     3  | sources:
[2025-07-02T03:47:34.549+0000] {subprocess.py:93} INFO -     4  |   - name: raw_source
[2025-07-02T03:47:34.550+0000] {subprocess.py:93} INFO -     5  |   database: ***
[2025-07-02T03:47:34.550+0000] {subprocess.py:93} INFO -     6  |   schema: driven_raw
[2025-07-02T03:47:34.551+0000] {subprocess.py:93} INFO -     7  |   tables:
[2025-07-02T03:47:34.551+0000] {subprocess.py:93} INFO -     8  |     - name: raw_batch_data
[2025-07-02T03:47:34.551+0000] {subprocess.py:93} INFO - 
[2025-07-02T03:47:34.551+0000] {subprocess.py:93} INFO -     Raw Error:
[2025-07-02T03:47:34.552+0000] {subprocess.py:93} INFO -     ------------------------------
[2025-07-02T03:47:34.552+0000] {subprocess.py:93} INFO -     while parsing a block collection
[2025-07-02T03:47:34.552+0000] {subprocess.py:93} INFO -       in "<unicode string>", line 4, column 3
[2025-07-02T03:47:34.552+0000] {subprocess.py:93} INFO -     did not find expected '-' indicator
[2025-07-02T03:47:34.552+0000] {subprocess.py:93} INFO -       in "<unicode string>", line 5, column 3
[2025-07-02T03:47:35.361+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-02T03:47:35.412+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-02T03:47:35.438+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_raw_data_pipeline, task_id=run_dbt_staging, run_id=manual__2025-07-02T03:47:24.314809+00:00, execution_date=20250702T034724, start_date=20250702T034731, end_date=20250702T034735
[2025-07-02T03:47:35.459+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-02T03:47:35.460+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task run_dbt_staging (Bash command failed. The command returned a non-zero exit code 2.; 929)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-02T03:47:35.513+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-02T03:47:35.562+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-02T03:47:35.564+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
